version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/dev.db

  db:
    image: "nouchka/sqlite3:latest"
    volumes:
      - db-data:/var/lib/sqlite/data

volumes:
  db-data:
